### ISSUE TITLE
 The engine "node" is incompatible with this module. Expected version ">=7.0.0

### ISSUE THREAD

**Issue by fer-ri** [rodrigogs/easyvpn#5]
Any plan to make it works with Node 4.x and 6.x ?

Thanks

**Comment by rodrigogs** [comment]
I didnt test it against node 4, but it may works. Could you try and tell us if it works?

**Comment by rodrigogs** [comment]
I think it will work if I just use strict mode in every js file. Tomorrow I'll take a look at it.

**Comment by ghost** [comment]
It does not work with node 4.x. I have this error when I run it :

/usr/local/lib/node_modules/easyvpn/bin/easyvpn.js:4
  let found = null;
  ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3


Node version: v4.2.6

**Comment by rodrigogs** [comment]
I just added suport for node 4. If you guys find any problem, please let me know.

**Comment by fer-ri** [comment]
Hi

i always get this result

```
$ sudo easyvpn -C JP
: No such file or directory
```

any idea?

My Node version

```
$ node -v
v6.9.4
```

Thanks
